sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_COVERAGE=true
        - EXECUTE_CS_CHECK=true
    - php: 7
    - php: hhvm
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 7
    - php: hhvm

notifications:
  email: false

before_install:
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - composer self-update
  - composer install

script:
  # PHPUnit
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover=coverage.clover ; fi
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then ./vendor/bin/phpunit ; fi
  # PHP CS Fixer
  - if [[ EXECUTE_CS_CHECK != 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
